name: Deploy
on: workflow_dispatch
jobs:
  connect-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: "1031766840445-compute@developer.gserviceaccount.com"
          project_id: "devops-team-1-430317"
          workload_identity_provider: "projects/1031766840445/locations/global/workloadIdentityPools/github/providers/my-repo"
      - name: Test gcloud
        run: gcloud projects list
      - name: check project
        run: gcloud config get project
      - id: 'deploy'
        run: gcloud run deploy game-server-service --port 8080 --source . --allow-unauthenticated --region=europe-west6